#!/usr/local/bin/perl -w
#-*-perl-*-
# Autogenerated by fd2pl from fdesign file gauge_gui.c
#
use X11::Xforms;
#

$plot_form = undef;
$plot = undef;
$xmin_input = undef;
$xmax_input = undef;
$matrix_index_input = undef;
$r_over_g_text = undef;
$file_menu = undef;
$action_menu = undef;
$help_menu = undef;
$options_menu = undef;
$second_intermediate_text = undef;
$filter_file_text = undef;

sub create_form_plot_form {
  $obj = undef;
  $plot_form = fl_bgn_form(FL_NO_BOX, 580, 480);
  $obj = fl_add_box(FL_UP_BOX, 0, 0, 580, 480, "");
  $obj = fl_add_frame(FL_UP_FRAME, 10, 10, 560, 20, "");
  $obj = fl_add_xyplot(FL_SQUARE_XYPLOT, 10, 60, 560, 330, "");
  $plot = $obj;
  fl_set_object_boxtype($obj, FL_FRAME_BOX);
  fl_set_object_lsize($obj, FL_MEDIUM_SIZE);
  $obj = fl_add_input(FL_NORMAL_INPUT, 280, 400, 90, 30, "Xmin");
  $xmin_input = $obj;
  fl_set_object_lsize($obj, FL_MEDIUM_SIZE);
  fl_set_object_callback($obj, "do_min_max", 0);
  $obj = fl_add_input(FL_NORMAL_INPUT, 420, 400, 90, 30, "Xmax");
  $xmax_input = $obj;
  fl_set_object_lsize($obj, FL_MEDIUM_SIZE);
  fl_set_object_callback($obj, "do_min_max", 0);
  $obj = fl_add_input(FL_NORMAL_INPUT, 170, 400, 50, 30, "Corr. Matrix index");
  $matrix_index_input = $obj;
  fl_set_object_lsize($obj, FL_MEDIUM_SIZE);
  fl_set_object_callback($obj, "do_matrix_index_input", 0);
  $obj = fl_add_text(FL_NORMAL_TEXT, 60, 40, 420, 20, "");
  $r_over_g_text = $obj;
  fl_set_object_lsize($obj, FL_MEDIUM_SIZE);
  fl_set_object_lalign($obj, FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
  $obj = fl_add_menu(FL_PULLDOWN_MENU, 10, 10, 70, 20, "File");
  $file_menu = $obj;
  fl_set_object_boxtype($obj, FL_NO_BOX);
  fl_set_object_lsize($obj, FL_MEDIUM_SIZE);
  fl_set_object_callback($obj, "do_file_menu", 0);
  fl_addto_menu($obj, "Open_intermediate_file");
  fl_addto_menu($obj, "Open_filter_file");
  fl_addto_menu($obj, "Edit_filter_file");
  fl_addto_menu($obj, "Exit");
  $obj = fl_add_menu(FL_PULLDOWN_MENU, 80, 10, 70, 20, "Action");
  $action_menu = $obj;
  fl_set_object_boxtype($obj, FL_NO_BOX);
  fl_set_object_lsize($obj, FL_MEDIUM_SIZE);
  fl_set_object_callback($obj, "do_action_menu", 0);
  fl_addto_menu($obj, "Replot");
  fl_addto_menu($obj, "Show_gauges");
  fl_addto_menu($obj, "Show_data");
  fl_addto_menu($obj, "Reset_x-axis");
  fl_addto_menu($obj, "Show_correlations");
  $obj = fl_add_menu(FL_PULLDOWN_MENU, 500, 10, 70, 20, "Help");
  $help_menu = $obj;
  fl_set_object_boxtype($obj, FL_NO_BOX);
  fl_set_object_lsize($obj, FL_MEDIUM_SIZE);
  fl_set_object_callback($obj, "do_help_menu", 0);
  fl_addto_menu($obj, "Help");
  $obj = fl_add_menu(FL_PULLDOWN_MENU, 150, 10, 70, 20, "Options");
  $options_menu = $obj;
  fl_set_object_boxtype($obj, FL_NO_BOX);
  fl_set_object_lsize($obj, FL_MEDIUM_SIZE);
  fl_set_object_callback($obj, "do_options_menu", 0);
  fl_addto_menu($obj, "Convective");
  fl_set_menu_item_mode($obj, 1, FL_PUP_BOX);
  fl_addto_menu($obj, "Stratiform");
  fl_set_menu_item_mode($obj, 2, FL_PUP_BOX);
  fl_addto_menu($obj, "Total");
  fl_set_menu_item_mode($obj, 3, FL_PUP_CHECK);
  fl_addto_menu($obj, "millimeters");
  fl_set_menu_item_mode($obj, 4, FL_PUP_RADIO);
  fl_addto_menu($obj, "dBz");
  fl_set_menu_item_mode($obj, 5, FL_PUP_RADIO);
  fl_addto_menu($obj, "Positive_only");
  fl_set_menu_item_mode($obj, 6, FL_PUP_BOX);
  $obj = fl_add_text(FL_NORMAL_TEXT, 30, 430, 540, 20, "Text");
  $second_intermediate_text = $obj;
  fl_set_object_boxtype($obj, FL_NO_BOX);
  fl_set_object_lalign($obj, FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  $obj = fl_add_text(FL_NORMAL_TEXT, 30, 450, 540, 20, "Text");
  $filter_file_text = $obj;
  fl_set_object_boxtype($obj, FL_NO_BOX);
  fl_set_object_lalign($obj, FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
  fl_end_form();
}
$corr_form = undef;
$r_browser = undef;

sub create_form_corr_form {
  $obj = undef;
  $corr_form = fl_bgn_form(FL_NO_BOX, 490, 170);
  $obj = fl_add_box(FL_UP_BOX, 0, 0, 490, 170, "");
  $obj = fl_add_browser(FL_NORMAL_BROWSER, 20, 30, 460, 90, "Gauge/Radar Correlations");
  $r_browser = $obj;
  fl_set_object_lsize($obj, FL_MEDIUM_SIZE);
  fl_set_object_lalign($obj, FL_ALIGN_TOP);
  fl_set_object_lstyle($obj, FL_FIXEDBOLD_STYLE);
  $obj = fl_add_button(FL_NORMAL_BUTTON, 20, 130, 110, 30, "Close");
  fl_set_object_color($obj, FL_COL1, FL_GREEN);
  fl_set_object_lsize($obj, FL_HUGE_SIZE);
  fl_set_object_lstyle($obj, FL_BOLD_STYLE);
  fl_set_object_callback($obj, "do_close", 0);
  fl_end_form();
}
$data_form = undef;
$data_browser = undef;

sub create_form_data_form {
  $obj = undef;
  $data_form = fl_bgn_form(FL_NO_BOX, 870, 300);
  $obj = fl_add_box(FL_UP_BOX, 0, 0, 870, 300, "");
  $obj = fl_add_browser(FL_NORMAL_BROWSER, 20, 30, 840, 220, " Net  Num   Range   yyyyjjj.fday      dBZ     Radar   Gauge      RadarT    GaugeT      RadarC     GaugeC     RadarS    GaugeS  Raintype");
  $data_browser = $obj;
  fl_set_object_lalign($obj, FL_ALIGN_TOP_LEFT);
  fl_set_object_lstyle($obj, FL_FIXEDBOLD_STYLE);
  $obj = fl_add_button(FL_NORMAL_BUTTON, 20, 260, 110, 30, "Close");
  fl_set_object_color($obj, FL_COL1, FL_GREEN);
  fl_set_object_lsize($obj, FL_HUGE_SIZE);
  fl_set_object_lstyle($obj, FL_BOLD_STYLE);
  fl_set_object_callback($obj, "do_close", 0);
  $obj = fl_add_button(FL_NORMAL_BUTTON, 130, 260, 200, 30, "Save to file");
  fl_set_object_color($obj, FL_COL1, FL_GREEN);
  fl_set_object_lsize($obj, FL_HUGE_SIZE);
  fl_set_object_lstyle($obj, FL_BOLD_STYLE);
  fl_set_object_callback($obj, "do_save_to_file_button", 0);
  fl_end_form();
}
$gauge_form = undef;
$gauge_browser = undef;

sub create_form_gauge_form {
  $obj = undef;
  $gauge_form = fl_bgn_form(FL_NO_BOX, 260, 360);
  $obj = fl_add_box(FL_UP_BOX, 0, 0, 260, 360, "");
  $obj = fl_add_browser(FL_HOLD_BROWSER, 20, 20, 230, 290, "");
  $gauge_browser = $obj;
  fl_set_object_callback($obj, "do_select_browser", 0);
  $obj = fl_add_button(FL_NORMAL_BUTTON, 20, 320, 110, 30, "Close");
  fl_set_object_color($obj, FL_COL1, FL_GREEN);
  fl_set_object_lsize($obj, FL_HUGE_SIZE);
  fl_set_object_lstyle($obj, FL_BOLD_STYLE);
  fl_set_object_callback($obj, "do_close", 0);
  fl_end_form();
}
$help_form = undef;
$help_browser = undef;

sub create_form_help_form {
  $obj = undef;
  $help_form = fl_bgn_form(FL_NO_BOX, 430, 360);
  $obj = fl_add_box(FL_UP_BOX, 0, 0, 430, 360, "");
  $obj = fl_add_browser(FL_NORMAL_BROWSER, 0, 0, 430, 330, "");
  $help_browser = $obj;
  fl_set_object_callback($obj, "do_help", 0);
  $obj = fl_add_button(FL_NORMAL_BUTTON, 0, 330, 110, 30, "Close");
  fl_set_object_color($obj, FL_COL1, FL_GREEN);
  fl_set_object_lsize($obj, FL_HUGE_SIZE);
  fl_set_object_lstyle($obj, FL_BOLD_STYLE);
  fl_set_object_callback($obj, "do_close", 0);
  fl_end_form();
}

sub create_the_forms {
  create_form_plot_form();
  create_form_corr_form();
  create_form_data_form();
  create_form_gauge_form();
  create_form_help_form();
}
1;
